requires:
- category: "system"
  name: "cos"
  version: ">=0"
- name: "k3s"
  category: "app"
  version: ">=0"

copy:
- package:
    category: "app"
    name: "epinio"
    version: ">=0"
  source: /usr/bin/epinio
  destination: /usr/bin/epinio
- package:
    name: "kubectl"
    category: "app"
    version: ">=0"
  source: /usr/bin/kubectl
  destination: /usr/bin/kubectl
- package:
    name: "helm"
    category: "app"
    version: ">=0"
  source: /usr/local/bin/helm
  destination: /usr/bin/helm

steps:
- zypper in -y {{.Values.additional_packages}}
- sed -i 's/:VERSION:/{{.Values.version}}/g' setup.yaml
- sed -i 's/:PRETTY_NAME:/{{.Values.brand_name}} v{{.Values.version}}/g' setup.yaml
- cp -fv 02_upgrades.yaml /system/oem/02_upgrades.yaml
- cp -fv 03_branding.yaml /system/oem/03_branding.yaml
- cp -fv 04_accounting.yaml /system/oem/04_accounting.yaml
- cp epinio.yaml /system/oem/
- yip setup.yaml

unpack: true

# Files to exclude from the final artifact 
# See also: https://luet-lab.github.io/docs/docs/concepts/packages/specfile/#excludingincluding-files-explictly
excludes:
- ^/var/cache/luet
- ^/luetbuild
- ^/srv/.*
- ^/root/.bash_history
- ^/run/reboot-needed

# Zypper
- ^/var/lib/zypp
- ^/var/cache/zypp
- ^/usr/share/zypper
- ^/usr/share/zypp
- ^/usr/share/zsh
- ^/usr/share/licenses/zypper
- ^/usr/bin/zypp-.*
- ^/usr/bin/zypper
- ^/usr/lib/zypp$
- ^/usr/lib/zypper
- ^/usr/lib/rpm
- ^/usr/bin/yzpper
- ^/usr/sbin/zypp-.*
- ^/usr/bin/zypp-.*
- ^/usr/bin/susetags2solv
- ^/run/zypp.*
- ^/etc/zypp
- ^/usr/bin/rpm.*
- ^/var/lib/rpm
- ^/usr/lib64/rpm-plugins 
# Yast
- ^/var/lib/YaST2

#- ^/usr/local
- ^/usr/local/bin
- ^/usr/local/go
- ^/usr/local/include
- ^/usr/local/lib.*
- ^/usr/local/man
- ^/usr/local/sbin
- ^/usr/local/share
- ^/usr/local/src
- ^/usr/local/games