stages:
   network:
     - name: "Start k3s and iscsid"
       systemctl: 
         start:
         - k3s
         - iscsid
     - name: "Setup Longhorn"
       commands:
       - |
          curl https://raw.githubusercontent.com/longhorn/longhorn/v1.1.0/deploy/longhorn.yaml | \
          sed -e 's/#- name: KUBELET_ROOT_DIR/- name: KUBELET_ROOT_DIR/g' -e 's$#  value: /var/lib/rancher/k3s/agent/kubelet$  value: /var/lib/kubelet$g'  | \
          sed -e 's|default-data-path:|default-data-path: /usr/local/rancher/longhorn|g' | \
          KUBECONFIG=/etc/rancher/k3s/k3s.yaml kubectl apply -f -
     - name: "Setup epinio"
       commands:
       - |
          if [ ! -e "/usr/local/epinio/epinio.yaml" ]; then
            mkdir -p /usr/local/epinio
            KUBECONFIG=/etc/rancher/k3s/k3s.yaml EPINIO_CONFIG=/usr/local/epinio/epinio.yaml epinio install
          fi
name: "Epinio install"