stages:
  default:
    - name: "Default systemd config"
      systemd:
        enable:
        - multi-user.target
        - getty@tty1
        - iscsid
        mask:
        - purge-kernels
      commands:
      - systemctl set-default multi-user.target
    - name: "Setup os-release"
      files:
      - path: /etc/os-release
        permissions: 0644
        owner: 0
        group: 0
      environment_file: /etc/os-release
      environment:
        NAME: "epinioOS"
        ID: "epinioOS"
        ANSI_COLOR: "0;32"
        BUG_REPORT_URL: "https://github.com/rancher-sandbox/epinio-appliance-demo-sample/issues"
        HOME_URL: "https://github.com/rancher-sandbox/epinio-appliance-demo-sample"
        DOCUMENTATION_URL: "https://github.com/rancher-sandbox/cOS-toolkit"
        VERSION: ":VERSION:"
        PRETTY_NAME: ":PRETTY_NAME:"
    - name: "Grub"
      files:
      - path: /etc/cos/grub.cfg
        content: |
              set timeout=10
              set default="${saved_entry}"
              set fallback="0 1 2"
              set gfxmode=auto
              set gfxpayload=keep
              insmod all_video
              insmod gfxterm
              menuentry "epinioOS" --id cos {
                search.fs_label COS_STATE root
                set img=/cOS/active.img
                set label=COS_ACTIVE
                loopback loop0 /$img
                set root=($root)
                source (loop0)/etc/cos/bootargs.cfg
                linux (loop0)$kernel $kernelcmd
                initrd (loop0)$initramfs
              }
              menuentry "epinioOS (fallback)" --id fallback {
                search.fs_label COS_STATE root
                set img=/cOS/passive.img
                set label=COS_PASSIVE
                loopback loop0 /$img
                set root=($root)
                source (loop0)/etc/cos/bootargs.cfg
                linux (loop0)$kernel $kernelcmd
                initrd (loop0)$initramfs
              }
              menuentry "epinioOS recovery" --id recovery {
                search.fs_label COS_RECOVERY root
                set img=/cOS/recovery.img
                set label=COS_SYSTEM
                loopback loop0 /$img
                set root=($root)
                source (loop0)/etc/cos/bootargs.cfg
                linux (loop0)$kernel $kernelcmd
                initrd (loop0)$initramfs
              }
        permissions: 0600
        owner: 0
        group: 0
      - path: /etc/cos/bootargs.cfg
        content: |
            set kernel=/boot/vmlinuz
            set kernelcmd="console=tty1 root=LABEL=$label iso-scan/filename=$img panic=5 security=selinux selinux=1"
            set initramfs=/boot/initrd
        permissions: 0600
        owner: 0
        group: 0