requires:
- name: "base"
  category: "distro"
  version: ">=0"
steps:
- |
    export DESIRED_VERSION=v${PACKAGE_VERSION%\+*} && \
    curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
