requires:
- name: "golang"
  category: "build"
  version: ">=0"
env:
- GOPATH=/luetbuild/go
- PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
- GO111MODULE=on
- CGO_ENABLED=0
- LDFLAGS="-s -w"
prelude:

- go get github.com/rakyll/statik
- zypper in -y git
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   git clone https://github.com/epinio/epinio.git epinio && \
   cd epinio && git checkout v$PACKAGE_VERSION -b build
steps:
- |
   cd epinio && make build && \
   cp -rf dist/epinio-linux-amd64 /usr/bin/epinio && \
   chmod +x /usr/bin/epinio