requires:
- name: "cos"
  category: "system"
  version: ">=0"

prelude:
- curl -LO "https://dl.k8s.io/release/v{{.Values.version}}/bin/linux/amd64/kubectl"
- curl -LO "https://dl.k8s.io/v{{.Values.version}}/bin/linux/amd64/kubectl.sha256"
- echo "$(<kubectl.sha256) kubectl" | sha256sum --check
steps:
- install -o root -g root -m 0755 kubectl /usr/bin/kubectl
