requires:
- name: "selinux-policies"
  category: "system"
  version: ">=0"
env:
- MODULE_NAME=epinioOS
steps:
- sed -i "s|^SELINUX=.*|SELINUX=permissive|g" /etc/selinux/config
- rm -rf /.autorelabel
- checkmodule -M -m -o ${MODULE_NAME}.mod ${MODULE_NAME}.te && semodule_package -o ${MODULE_NAME}.pp -m ${MODULE_NAME}.mod
- semodule -i ${MODULE_NAME}.pp